services:
  searxng:
    image: searxng/searxng
    container_name: r2-searxng
    ports:
      - "8888:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    restart: unless-stopped
    environment:
      - SEARXNG_BASE_URL=http://localhost:8888
